### ISSUE TITLE
End To End Performance with GPU-native

### ISSUE THREAD

**Issue by cupdike** [samrere/pytortto#3]
It would be interesting to compare the end-to-end performance against Pytorch if the data access time were also factored in, considering it is possibly to load data into the CuPy like this:
https://xarray.dev/blog/xarray-kvikio

Of course, it would depend a lot on how the data and the training job interact....

**Comment by samrere** [comment]
Hi @cupdike thank you for your suggestion. It's great to know that we can load data directly into gpu, and I'll look deeper when I implement dataloaders later.

> compare the end-to-end performance against Pytorch if the data access time were also factored in

they are already taken into account when comparing speed with pytorch because I used the same pytorch dataloader to load data. In each loop, pytorch tensors will be converted to numpy arrays, then convert to tortto tensors. All computations after that is done in tortto.
