### ISSUE TITLE
Numpy Version 1.24 Requirement 

### ISSUE THREAD

**Issue by mrn1522** [samrere/pytortto#5]
Hello,

Thanks for creating a great project. Can you explain why the Numpy minimum version is 1.24? I removed the check and seemed to work correctly with no errors?

Can you also provide an example of loading one of the Resnet models under examples and how you would do inference on images?

**Comment by samrere** [comment]
Hi mahearn22,
the minimum numpy version was to make sure it has the weak promotion state flag. This is to make sure operations on numpy arrays don't change its precision:
```python
import numpy as np

print(np.__version__)
x = np.array([1, 2, 3]).astype('f')
print(f'dtype: {x.dtype}')
y = x / 123456
print(f'dtype: {y.dtype}')
```
```
1.24.3
dtype: float32
dtype: float64
```
as you can see, a small float32 divided by some large number changes its dtype to float64, this is pretty common in modules such as `nn.NLLLoss` because the default reduction is 'mean', which means you need to divide the tensor with its size. Without this flag, the whole training process will be in float64, which takes much more space, much slower, and unnecessary.  
Compare with this:
```python
import os
os.environ['NPY_PROMOTION_STATE'] = 'weak'
import numpy as np

print(np.__version__)
x = np.array([1, 2, 3]).astype('f')
print(f'dtype: {x.dtype}')
y = x / 123456
print(f'dtype: {y.dtype}')
```
```
1.24.3
dtype: float32
dtype: float32
```
To run one of the examples, like resnet18,
1. clone the repo
2. follow the instructions [here](https://github.com/samrere/pytortto/tree/main/examples/resnet/preact_resnet18), download the trained model and put it in the `models` folder.
3. open preact_resnet18.ipynb using jupyter notebook
4. go to Kernel -> Restart & Run All
5. it will now run the cells one by one. Note on cell 4 it will download the CIFAR10 dataset automatically.
6. wait until it throw an error at cell 9 saying `OSError: log.txt already exists`. This is to prevent overwrite existing training logs. You can check the `log.txt` at the `log` folder. We can skip this cell because we already have the trained model and no need to do it again.
7. manually run the following cells one by one, to plot the error, test on validation, and plot prediction results on CIFAR10.

That's it! If you want to train from scratch and see pytortto in action, you can delete the content in `log` folder, then press Restart & Run All. On my computer with rtx2080ti it takes 1 min each epoch so 180 epochs takes about 3 hours.

**Comment by samrere** [comment]
> I removed the check and seemed to work correctly with no errors

You are not seeing errors because I commented out all assertions at every node during forward and backward propagation: https://github.com/samrere/pytortto/blob/main/src/tortto/autograd/function.py. Technically they are not errors, they just make training super slow and take much space

**Comment by mrn1522** [comment]
Perfect, thanks, it works very well!
